### ISSUE TITLE
🐛 [BUG] Filtering not working in "Brand / Defaults" and "Materials"

### ISSUE THREAD

**Issue by BlackRose01** [MarksMakerSpace/filament-profiles#27]
**Describe the bug**
The function to filter the list will always show "No items found".

**To Reproduce**
1. Go to 'Brand / Defaults' or 'Materials'
2. Click in Search Field
3. Type any filterable value in the field (e.g. SUNLU or sunlu) - Capitalization is uninteresting
4. Result: "No items found"

**Expected behavior**
A list with the filtered result

**Screenshots**
![Screenshot 2024-12-04 203304](https://github.com/user-attachments/assets/26f8e605-ea0e-4459-8055-864646cef21c)
![Screenshot 2024-12-04 203325](https://github.com/user-attachments/assets/05bd5703-9c08-4bac-8ba3-0f5fb382afa3)

----

![Screenshot 2024-12-04 203351](https://github.com/user-attachments/assets/6e3c1c8f-6ceb-47fc-a28c-fffaf295db9c)
![Screenshot 2024-12-04 203410](https://github.com/user-attachments/assets/5fe143b7-d377-4d1d-b286-6d7b75eb3800)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser firefox
 - Version 133.

**Comment by markcarroll** [comment]
crap, I think I broke this last night. thanks for catching @BlackRose01

**Comment by markcarroll** [comment]
this should now be fixed.

**Comment by BlackRose01** [comment]
@markcarroll Sorry for reopening the issue but the problem still exists on the Materials page
[https://3dfilamentprofiles.com/materials](https://3dfilamentprofiles.com/materials)

**Comment by markcarroll** [comment]
hey don't apologize. I appreciate the assist.  I am signing you up as my official test team. 

That page is fixed and deployed now. Thanks again.
