### ISSUE TITLE
🐛 [BUG] Text being truncated with long filament types

### ISSUE THREAD

**Issue by minsis** [MarksMakerSpace/filament-profiles#88]
**Describe the bug**
Text on the label is truncated for longer filament types.

https://3dfilamentprofiles.com/filaments/3340/details

**Comment by minsis** [comment]
This seems to be happening for label life default image and PNG, but not the native format.


Default:

<img width="1046" alt="Image" src="https://github.com/user-attachments/assets/479a75d5-7576-4a69-b8c6-5d7c34a6d5ef" />

Native:

<img width="1046" alt="Image" src="https://github.com/user-attachments/assets/514f332a-dfc9-4c31-afde-562bfdbc9616" />

PNG:

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/5ea64e25-4517-4c1c-9096-8bc44abfc6a9" />

**Comment by markcarroll** [comment]
this is now fixed

**Comment by minsis** [comment]
This is still an issue: https://3dfilamentprofiles.com/filaments/3629/details

**Comment by markcarroll** [comment]
ok @minsis I have updated the function to resize that box yet again (can they get any longer?).  Now it maxes out at 30 characters and after that truncates the string, since I think we get to the point it becomes illegible if we go any smaller.  Refresh the page and let me know if that is looking any better.

**Comment by minsis** [comment]
These day who knows 🤷. Polymaker is rebranding their entire lineup with Panachroma. Just doing a website spot check it looks like maybe the longest name they have is `Panachroma Gradient Matte`

**Comment by markcarroll** [comment]
I think we might also need to truncate the PLA+/PRO to just PLA+ for longer labels. Sorry for the delay on getting this back out, but I screwed up the database on that last deploy that you caught. Think it is fixed now. Serves me right for relying on AI to help redo a DB query while running a fever. Moral - never trust the AI.

**Comment by minsis** [comment]
It's all good. I also agree about maybe changing it to PLA+.

Not sure what point where you cut off the readability of the label and the need for having all the numbers. Not sure if there's any kind of way to abbreviate some of  more lengthy words for the label. Similar applications do things like this where they have a word, the pluralized word, and an abbreviated word all associated to said word.
